name: ngx-sweetalert2
root: ./

windows:
  - yarn:
      layout: even-horizontal
      panes:
        - yarn
        - yarn outdated

  - lib/demo:
      layout: even-horizontal
      panes:
        -
          - echo Waiting a bit for the library to compile a first time...; sleep 10
          - yarn serve
        - yarn build:lib --watch
